### ISSUE TITLE
Please update the package

### ISSUE THREAD

**Issue by gaelfortin** [EricEdwardBryant/rothfreezer#32]
Hi Eric, could you update the package please?

Thanks,
Gael

**Comment by EricEdwardBryant** [comment]
All set! Updated in e670f3c

**Comment by EricEdwardBryant** [comment]
Not critical, but at some point in the future, please update your date entries from 5/1/2019 format to 2019-05-01 format. And don't forget to add the freezer addresses (shelf rack etc.) at some point :see_no_evil:

Thanks for submitting the issue on GitHub! :tada: :thumbsup:
