### ISSUE TITLE
Not compatible with dplyr 1.0

### ISSUE THREAD

**Issue by RobertJDReid** [EricEdwardBryant/rothfreezer#35]
The function `view_strain_collection_keys` uses a standard evaluation `select_` function that is obsolete starting in dplyr 1.0. Needs to be updated to use tidyselect

**Comment by EricEdwardBryant** [comment]
Nice job with the pull request! Closing this issue as it was fixed in your pull request #36 along with an update to the database in 06f6c31005d3b7f4d3e45155b674fdd114353499 and a fix for a newly deprecated function warning in f9a520212acff39e69f53b3e6655c5644e34d19b
